import type { Metadata } from "next";
import { Geist, ADLaM_Display } from "next/font/google";
import "./globals.css";
import Menu from "@/components/Menu";
import Counter from "@/components/Counter";

type IProps = {
  params: Promise<{ id: string }>;
  // searchParams: Promise<{ [key: string]: string | string[] | undefined }>;
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = ADLaM_Display({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
});

// 静态元数据;
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

//动态元数据
export async function generateMetadata({ params }: IProps) {
  const data = await params;
  console.log("params", data);
  return {
    title: "Generate Metadata",
    description: "Generated by generateMetadata",
  } as Metadata;
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.className} antialiased`}
      >
        <main className="border border-amber-700 w-full h-vh">
          <Menu />
          <div className="text-[24px]">
            layout页面中的状态在路由跳转后不会重置
          </div>
          <Counter />
          {children}
        </main>
      </body>
    </html>
  );
}
